version: '3'

services:
  postgres:
    container_name: nest_postgres
    image: postgres:14.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: default_database
    ports:
      - '5432:5432'
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
