version: '3'

services:
  postgres:
    container_name: nest_postgres
    image: postgres:14.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: default_database
    ports:
      - '5432:5432'
    volumes:
      - postgres:/data/postgres

  pgweb:
    container_name: pgweb
    image: sosedoff/pgweb
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/default_database?sslmode=disable
      - AUTH_USER=postgres
      - AUTH_PASS=postgres
    ports:
      - "8081:8081"
    links:
      - postgres:postgres
    depends_on:
      - postgres

volumes:
  postgres:
